// Generated by CoffeeScript 1.7.1
(function() {
  var pageTransitions;

  pageTransitions = new PageTransitions(jQuery('#pt-main'), jQuery('.pt-page'));

  jQuery('.flip').on('click', function() {
    return pageTransitions.flip();
  });

}).call(this);
